events {}

http {
  server {
    listen 8080;
    listen [::]:8080 ipv6only=off;
    server_name _;

    location / {
      return 200 "nginx ok\n";
    }

    location /api/ {
      proxy_pass http://127.0.0.1:7070/;
      proxy_set_header Host $host;
    }

    location /live/ {
      proxy_pass http://127.0.0.1:8888/live/;
      proxy_set_header Host $host;
    }
  }
}
