[supervisord]
nodaemon=true
logfile=/dev/stdout

[program:xvfb]
command=/usr/bin/Xvfb :99 -screen 0 1920x1080x24 -ac +extension RANDR
autorestart=true
priority=10

[program:pulseaudio]
command=/usr/bin/pulseaudio --system --disallow-exit --exit-idle-time=-1
autorestart=true
priority=20

[program:mediamtx]
command=/opt/mediamtx/mediamtx /app/mediamtx.yml
autorestart=true
priority=30

[program:control]
command=/usr/bin/node /app/control.js
autorestart=true
priority=40

[program:browser]
command=/usr/bin/chromium-browser --no-sandbox --disable-setuid-sandbox --disable-dev-shm-usage --autoplay-policy=no-user-gesture-required --window-size=1920,1080 --start-fullscreen about:blank
environment=DISPLAY=":99"
autostart=false
autorestart=true
priority=50

[program:controller]
command=/usr/bin/node /app/stream.js
environment=DISPLAY=":99"
autostart=false
autorestart=false
priority=60

[program:ffmpeg]
command=/app/ffmpeg.sh
environment=DISPLAY=":99"
autostart=false
autorestart=true
priority=70
